### ISSUE TITLE
`realloc` may not keep the memory alignment of memory allocated by `posix_memalign`

### ISSUE THREAD

**Issue by CxdInitial** [daniel5151/libc_alloc#2]
see https://stackoverflow.com/questions/9078259/does-realloc-keep-the-memory-alignment-of-posix-memalign

**Comment by daniel5151** [comment]
Huh, would you look at that. I mean, in hindsight, that certainly makes sense.

And yep, checking the [Rust standard library's implementation](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unix/alloc.rs), we see that there is a _fast path_ that uses `realloc` directly for small alignments, but falls back to a manual allocate-copy-free otherwise: https://github.com/rust-lang/rust/blob/master/library/std/src/sys_common/alloc.rs.

Truth be told, the more I read the Rust source, the more I realize I probably should have just copied its implementation wholesale... I guess because I wanted to keep things simple? Who knows...

Anyways, yes, this is a bug, and I will fix it. I'll put it on my TODO list for this weekend, but if it's urgent, feel free to open a quick PR to fix this issue. I'd merge+push up a new version of the library with the fix to crates.io lickety split.

**Comment by CxdInitial** [comment]
Sorry for the close and reopen, I clicked the button accidently.

**Comment by corecode** [comment]
this can be closed now.
